/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.genoscope.reader;

import com.genoscope.types.Chromosome;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Furkan Mustafa Akdemir
 */
public class Reader {
	public Chromosome readFile(String path){
		 final JPanel panel = new JPanel();
		//variables for extension check
		String extension;
		int lastInd;
		
		//get extension
		lastInd=path.lastIndexOf('.');
		extension=path.substring(lastInd+1);
		System.out.println(extension);
		
		if(extension.equals("bed")) //If format is bed then initialize a bed format
			return new BED().readFile(path);//return chromosome object generated by BED
		else if(extension.equals("bla"))
			return null;
		JOptionPane.showMessageDialog(panel, "Unsupported file extension:"+path,
				"Warning", JOptionPane.WARNING_MESSAGE);
		return null;
	}
}
